# Hydrogen

spacing         = 2
padding         = 0
hide_ascii      = true
separator       = ">"
key_color       = "Cyan"
separator_color = "White"

[palette]
type = "Full"
visible = false

[bar]
glyph           = "ß‹"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = true

[box]
border          = "plain"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "Host"
os              = "OS"
kernel          = "Kernel"
wm              = "WM"
distro          = "Distro"
terminal        = "Terminal"
packages        = "Packages"
uptime          = "Uptime"
memory          = "Memory"
cpu_load        = "CPU Load"
cpu             = "CPU"
gpu             = "GPU"
disk_space      = "Disk Space"
