theme = "base16_terminal"

[editor]
line-number = "relative"
mouse = false
middle-click-paste = false
auto-format = true
auto-save = true
color-modes = true
bufferline = "multiple"
scrolloff = 4

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.lsp]
display-messages = true

[keys.normal]
w = ":w"
C-S-j = ":sh javac $(find -name '*.java') && java Driver &> DebugPipe"
C-S-c = ":sh gcc main.c -o main && ./main &> DebugPipe"
C-S-k = ":sh pkill java"
